[package]
name = "day7"
version = "0.1.0"
authors = ["Edward A King <eaking@us.ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "day7"
path = "src/day7.rs"

[dependencies]
petgraph = "0.5.1"
regex = "1"